source 'https://rubygems.org'

gem 'github-pages', '106'
gem 'jekyll-paginate'
gem 'jekyll'
gem 'jekyll-archives'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-readme-index'
gem 'execjs'
gem 'therubyracer'
gem 'rouge'
gem 'jemoji'
